stages:
- build
- upload
- cleanup

#Global variables
variables:
    QT_PATH_ANDROID: "/home/tools/Qt-OpenSource/5.14.1/android"
    QT_PATH_DESKTOP: "/home/tools/Qt-OpenSource/5.14.1/gcc_64"
    ANDROID_SDK_ROOT: "/home/tools/android/android-sdk-linux"
    ANDROID_NDK_ROOT: "/home/tools/android/android-ndk-r21"
    ANDROID_NDK_HOME: "$ANDROID_NDK_ROOT"
    ANDROID_NDK_PLATFORM: "android-21"
    ANDROID_SIGN_COMMANDS: "--sign $CI_PROJECT_DIR/Gaiachain/platforms/android/cert/gaiachain_cert.keystore gaiachain --storepass $ANDROID_KEYSTORE_PASS"
    ANDROID_NDK_TOOLCHAIN_VERSION: "4.9"
    ANDROID_TARGET_PLATFORM: "android-28"
    ABIS: "armeabi-v7a"
    #ABIS: "armeabi-v7a arm64-v8a x86 x86_64"
    JAVA_HOME: "/home/tools/jdk8"
    PROJECT_NAME: "Gaiachain"
    SEAFILE_SERVER: "https://seafile.milosolutions.com"
    SEAFILE_REPO_ID: "3df1ca9d-bc95-4424-b061-3f98c91dae3b"

.common: &common
  allow_failure: false
  before_script:
    - export OUT_PACKAGES_DIR="$HOME/packages/$CI_BUILD_REF"
    - mkdir -p $OUT_PACKAGES_DIR
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - git submodule status --recursive

.only-common: &only-common
  only:
    - dev
    - master
    - tags
    - merge_requests

# Linux
linux_build:
  <<: *common
  <<: *only-common
  tags:
    - LinuxDesktop
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    #  CONFIG+=lto
    - $QT_PATH_DESKTOP/bin/qmake QMAKE_CC=gcc-9 QMAKE_CXX=g++-9
    - make -j3
    - make install INSTALL_ROOT=$CI_PROJECT_DIR/build

# Android
android_release-server_build:
  <<: *common
  <<: *only-common
  tags:
    - LinuxAndroid
  stage: build
  when: manual
  allow_failure: true
  variables:
    BUILD_TYPE: "release"
    PACKAGE_NAME: "Gaiachain_release-server_$CI_COMMIT_REF_SLUG.apk"
  script:
    - cd $CI_PROJECT_DIR
    - cp -r /home/projects/Gaiachain/dependencies/OpenSSL/OpenSSL $CI_PROJECT_DIR/Gaiachain/3rdparty/OpenSSL
    - $QT_PATH_ANDROID/bin/qmake CONFIG+=release_server ANDROID_ABIS=$ABIS
    - cat Makefile
    - make -j3
    - make install INSTALL_ROOT=$CI_PROJECT_DIR/Gaiachain/android-build
    - cd $CI_PROJECT_DIR
    - ls -la
    - cd Gaiachain
    - ls -la
    - $QT_PATH_ANDROID/bin/androiddeployqt --output android-build --input android-$PROJECT_NAME-deployment-settings.json --android-platform $ANDROID_TARGET_PLATFORM --gradle --release $ANDROID_SIGN_COMMANDS
    - cp -f android-build/build/outputs/apk/release/android-build-$BUILD_TYPE-signed.apk $OUT_PACKAGES_DIR/$PACKAGE_NAME

android_dev-server_build:
  <<: *common
  <<: *only-common
  tags:
    - LinuxAndroid
  stage: build
  variables:
    BUILD_TYPE: "release"
    PACKAGE_NAME: "Gaiachain_dev-server_$CI_COMMIT_REF_SLUG.apk"
  script:
    - cd $CI_PROJECT_DIR
    - cp -r /home/projects/Gaiachain/dependencies/OpenSSL/OpenSSL $CI_PROJECT_DIR/Gaiachain/3rdparty/OpenSSL
    - $QT_PATH_ANDROID/bin/qmake CONFIG+=use_combobox ANDROID_ABIS=$ABIS
    - cat Makefile
    - make -j3
    - make install INSTALL_ROOT=$CI_PROJECT_DIR/Gaiachain/android-build
    - cd $CI_PROJECT_DIR
    - ls -la
    - cd Gaiachain
    - ls -la
    # Available in Qt 5.14.1
    #- make apk
    - $QT_PATH_ANDROID/bin/androiddeployqt --output android-build --input android-$PROJECT_NAME-deployment-settings.json --android-platform $ANDROID_TARGET_PLATFORM --gradle --release $ANDROID_SIGN_COMMANDS
    - cp -f android-build/build/outputs/apk/release/android-build-$BUILD_TYPE-signed.apk $OUT_PACKAGES_DIR/$PACKAGE_NAME

android_dev-server_no-combobox_build:
  <<: *common
  <<: *only-common
  tags:
    - LinuxAndroid
  stage: build
  when: manual
  allow_failure: true
  variables:
    BUILD_TYPE: "release"
    PACKAGE_NAME: "Gaiachain_dev-server_$CI_COMMIT_REF_SLUG.apk"
  script:
    - cd $CI_PROJECT_DIR
    - cp -r /home/projects/Gaiachain/dependencies/OpenSSL/OpenSSL $CI_PROJECT_DIR/Gaiachain/3rdparty/OpenSSL
    - $QT_PATH_ANDROID/bin/qmake CONFIG-=use_combobox ANDROID_ABIS=$ABIS
    - cat Makefile
    - make -j3
    - make install INSTALL_ROOT=$CI_PROJECT_DIR/Gaiachain/android-build
    - cd $CI_PROJECT_DIR
    - ls -la
    - cd Gaiachain
    - ls -la
    - $QT_PATH_ANDROID/bin/androiddeployqt --output android-build --input android-$PROJECT_NAME-deployment-settings.json --android-platform $ANDROID_TARGET_PLATFORM --gradle --release $ANDROID_SIGN_COMMANDS
    - cp -f android-build/build/outputs/apk/release/android-build-$BUILD_TYPE-signed.apk $OUT_PACKAGES_DIR/$PACKAGE_NAME

upload_job:
  <<: *common
  only:
    - master
    - dev
    - schedules
    #- merge_requests
  tags:
    - LinuxAndroid
  stage: upload
  when: on_success
  variables:
    UPLOAD_SCRIPT: "$CI_PROJECT_DIR/milo/mscripts/seafile/upload_to_seafile.sh"
  script:
    - export BUILD_TIMESTAMP=`date +%Y-%m-%d`
    - cd $OUT_PACKAGES_DIR
    - ls -lh
    - APK_PACKAGES=*.apk
    - for PACKAGE in $APK_PACKAGES; do mv $PACKAGE "$BUILD_TIMESTAMP"_"$PACKAGE"; done
    - for PACKAGE in * ; do $UPLOAD_SCRIPT -f $PACKAGE -s $SEAFILE_SERVER -r $SEAFILE_REPO_ID -d "/charcoal/packages/" -t $SEAFILE_API_TOKEN; done

cleanup:
  <<: *common
  <<: *only-common
  tags:
    - LinuxDesktop
    - LinuxAndroid
  stage: cleanup
  when: always
  script:
    - ls -lh $OUT_PACKAGES_DIR
    - rm -rf $OUT_PACKAGES_DIR
