stages:
- build
- upload
- cleanup

#Global variables
variables:
    QT_PATH_ANDROID: "/home/tools/Qt-OpenSource/5.14.1/android"
    QT_PATH_DESKTOP: "/home/tools/Qt-OpenSource/5.14.1/gcc_64"
    ANDROID_SDK_ROOT: "/home/tools/android/android-sdk-linux"
    ANDROID_NDK_ROOT: "/home/tools/android/android-ndk-r21"
    ANDROID_NDK_HOME: "$ANDROID_NDK_ROOT"
    ANDROID_NDK_PLATFORM: "android-21"
    ANDROID_SIGN_COMMANDS: "--sign $CI_PROJECT_DIR/Gaiachain/platforms/android/cert/gaiachain_cert.keystore gaiachain --storepass $ANDROID_KEYSTORE_PASS"
    ANDROID_NDK_TOOLCHAIN_VERSION: "4.9"
    ANDROID_TARGET_PLATFORM: "android-28"
    ABIS: "armeabi-v7a"
    #ABIS: "armeabi-v7a arm64-v8a x86 x86_64"
    JAVA_HOME: "/home/tools/jdk8"
    PROJECT_NAME: "Gaiachain"
    SEAFILE_SERVER: "https://seafile.milosolutions.com"
    SEAFILE_REPO_ID: "3df1ca9d-bc95-4424-b061-3f98c91dae3b"
    # android-build variables
    QMAKE_CONFIG: "CONFIG+=release_server"
    BUILD_TYPE: "release"
    FLAVOR: "none"

.common: &common
  allow_failure: false
  before_script:
    - export OUT_PACKAGES_DIR="$HOME/packages/$CI_BUILD_REF"
    - mkdir -p $OUT_PACKAGES_DIR
    - mkdir -p $OUT_PACKAGES_DIR/cocoa
    - mkdir -p $OUT_PACKAGES_DIR/charcoal
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - git submodule status --recursive

.only-common: &only-common
  only:
    - dev
    - master
    - tags
    - merge_requests

# Script below is shared between all Linux builds
.linux-build: &linux-build
  tags:
    - LinuxDesktop
  script:
  - cd $CI_PROJECT_DIR
  - cp -r /home/projects/Gaiachain/dependencies/OpenSSL/OpenSSL $CI_PROJECT_DIR/Gaiachain/3rdparty/OpenSSL
  #  CONFIG+=lto
  - $QT_PATH_DESKTOP/bin/qmake CONFIG+=$FLAVOR QMAKE_CC=gcc-9 QMAKE_CXX=g++-9
  - make -j3
  - make install INSTALL_ROOT=$CI_PROJECT_DIR/build

# Script below is shared between all Android builds
.android-build: &android-build
  tags:
    - LinuxAndroid
  script:
    - cd $CI_PROJECT_DIR
    - cp -r /home/projects/Gaiachain/dependencies/OpenSSL/OpenSSL $CI_PROJECT_DIR/Gaiachain/3rdparty/OpenSSL
    - $QT_PATH_ANDROID/bin/qmake CONFIG+=$FLAVOR $QMAKE_CONFIG ANDROID_ABIS=$ABIS
    - cat Makefile
    - make -j3
    - make install INSTALL_ROOT=$CI_PROJECT_DIR/Gaiachain/android-build
    - cd $CI_PROJECT_DIR
    - ls -la
    - cd Gaiachain
    - ls -la
    - $QT_PATH_ANDROID/bin/androiddeployqt --output android-build --input android-$PROJECT_NAME-deployment-settings.json --android-platform $ANDROID_TARGET_PLATFORM --gradle --release $ANDROID_SIGN_COMMANDS
    - cp -f android-build/build/outputs/apk/release/android-build-$BUILD_TYPE-signed.apk $OUT_PACKAGES_DIR/$FLAVOR/$PACKAGE_NAME

# Linux
linux-cocoa:
  <<: *common
  <<: *only-common
  <<: *linux-build
  stage: build
  when: manual
  allow_failure: true
  variables:
    QMAKE_CONFIG: ""
    FLAVOR: "cocoa"

linux-charcoal:
  <<: *common
  <<: *only-common
  <<: *linux-build
  stage: build
  when: manual
  allow_failure: true
  variables:
    QMAKE_CONFIG: ""
    FLAVOR: "charcoal"

# Android Cocoa
android-release-cocoa:
  <<: *common
  <<: *only-common
  <<: *android-build
  stage: build
  when: manual
  allow_failure: true
  variables:
    PACKAGE_NAME: "${CI_JOB_NAME}-$CI_COMMIT_REF_SLUG.apk"
    QMAKE_CONFIG: "CONFIG+=release_server"
    FLAVOR: "cocoa"

android-dev-cocoa-combobox:
  <<: *common
  <<: *only-common
  <<: *android-build
  stage: build
  variables:
    PACKAGE_NAME: "${CI_JOB_NAME}-$CI_COMMIT_REF_SLUG.apk"
    QMAKE_CONFIG: "CONFIG+=use_combobox"
    FLAVOR: "cocoa"

android-dev-cocoa:
  <<: *common
  <<: *only-common
  <<: *android-build
  stage: build
  when: manual
  allow_failure: true
  variables:
    PACKAGE_NAME: "${CI_JOB_NAME}-$CI_COMMIT_REF_SLUG.apk"
    QMAKE_CONFIG: ""
    FLAVOR: "cocoa"

# Android Charcoal
android-release-charcoal:
  <<: *common
  <<: *only-common
  <<: *android-build
  stage: build
  when: manual
  allow_failure: true
  variables:
    PACKAGE_NAME: "${CI_JOB_NAME}-$CI_COMMIT_REF_SLUG.apk"
    QMAKE_CONFIG: "CONFIG+=release_server"
    FLAVOR: "charcoal"

android-dev-charcoal-combobox:
  <<: *common
  <<: *only-common
  <<: *android-build
  stage: build
  variables:
    PACKAGE_NAME: "${CI_JOB_NAME}-$CI_COMMIT_REF_SLUG.apk"
    QMAKE_CONFIG: "CCONFIG+=use_combobox"
    FLAVOR: "charcoal"

android-dev-charcoal:
  <<: *common
  <<: *only-common
  <<: *android-build
  stage: build
  when: manual
  allow_failure: true
  variables:
    PACKAGE_NAME: "${CI_JOB_NAME}-$CI_COMMIT_REF_SLUG.apk"
    QMAKE_CONFIG: ""
    FLAVOR: "charcoal"

upload_job:
  <<: *common
  only:
    - master
    - dev
    - schedules
    - merge_requests
  tags:
    - LinuxAndroid
  stage: upload
  when: on_success
  variables:
    UPLOAD_SCRIPT: "$CI_PROJECT_DIR/milo/mscripts/seafile/upload_to_seafile.sh"
  script:
    - export BUILD_TIMESTAMP=`date +%Y-%m-%d`
    - cd $OUT_PACKAGES_DIR/cocoa
    - ls -lh
    - APK_PACKAGES=*.apk
    - for PACKAGE in $APK_PACKAGES; do mv $PACKAGE "$BUILD_TIMESTAMP"-"$PACKAGE"; done
    - for PACKAGE in * ; do $UPLOAD_SCRIPT -f $PACKAGE -s $SEAFILE_SERVER -r $SEAFILE_REPO_ID -d "cocoa/packages" -t $SEAFILE_API_TOKEN; done
    - cd $OUT_PACKAGES_DIR/charcoal
    - ls -lh
    - APK_PACKAGES=*.apk
    - for PACKAGE in $APK_PACKAGES; do mv $PACKAGE "$BUILD_TIMESTAMP"-"$PACKAGE"; done
    - for PACKAGE in * ; do $UPLOAD_SCRIPT -f $PACKAGE -s $SEAFILE_SERVER -r $SEAFILE_REPO_ID -d "charcoal/packages" -t $SEAFILE_API_TOKEN; done

cleanup:
  <<: *common
  <<: *only-common
  tags:
    - LinuxDesktop
    - LinuxAndroid
  stage: cleanup
  when: always
  script:
    - ls -lh $OUT_PACKAGES_DIR
    - rm -rf $OUT_PACKAGES_DIR
